### ISSUE TITLE
Not working on a Mac

### ISSUE THREAD

**Issue by mattslater** [cstgrid/k8comp#4] opened 2018-01-03 18:28 UTC
I have been having problems getting k8comp to work on my mac, but I have just managed to get it working. Thought I would create an issue so it could be potentially fixed if @catalinpan has time or even wants to change it! I don't think adding the extra bit of code will break anything but you may have a different opinion ;)

This is my method of getting k8comp working on my mac, there are probably many ways to resolve this though.

First of all you need you need to have brew installed to get the extra things needed to get this to work, I used cakebrew.

I reinstalled sed, this time installing the GNU version of sed (package name: gnu-sed). Then I installed ed.

         Versions at the time of writing:
               - sed (GNU sed) 4.4
               - GNU ed 1.14.2

Then I edited the code: 

Changing line 416:
FROM:
             _$(cat ${3})_
TO:
             _$(cat "${3}" | sed -e 's/^[[:space:]]*//')_

New block of code:

```
add_multiline_var () { 
ed ${1}  > /dev/null 2>&1 << __EOF__
${2}i
$(cat "${3}" | sed -e 's/^[[:space:]]*//')
.
wq
__EOF__
}
```
 
Hope this helps anyone trying to use k8comp on a mac.

**Comment by catalinpan** [comment] 2018-01-04 10:35
Thanks Matt for raising this. I will test and push the fix you've mentioned.

**Comment by mattslater** [comment] 2018-01-04 11:47
Hey Catalin,

I have just found a problem with my solution. I will work on it and get back to you with an updated solution.

**Comment by mattslater** [comment] 2018-01-04 12:26
Okay so just to explain the issue I was having, as I didn't do that in the previous post...

I was having a problem with a leading whitespace causing kubectl to complain when trying to apply it. With the current code the first two lines have a leading whitespace. The same problem happens with the deployment strategy. This will be an issue whenever using add_multiline_var.

 A quick fix is to remove the "*" from $(cat "${3}" | sed -e 's/^[[:space:]]*//') so you are left with:
               $(cat "${3}" | sed -e 's/^[[:space:]]//')

This will only remove the first instance on whitespace, which works for me but will break things for people not having problems currently. 

Example output with unedited code:
```
---
 apiVersion: extensions/v1beta1
 kind: Deployment
metadata:
  labels:
    name: app
  name: app
  namespace: webapp-prod
spec:
   strategy:
     rollingUpdate:
       maxSurge: 10%
       maxUnavailable: 0
   revisionHistoryLimit: 10
```

Example with using "$(cat "${3}" | sed -e 's/^[[:space:]]*//')" :
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: app
  name: app
  namespace: webapp-prod
spec:
strategy:
rollingUpdate:
maxSurge: 10%
maxUnavailable: 0
revisionHistoryLimit: 10
```

After the change with "$(cat "${3}" | sed -e 's/^[[:space:]]//')" :
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: app
  name: app
  namespace: web-prod
spec:
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
  revisionHistoryLimit: 10
  replicas: 1
```

**Comment by catalinpan** [comment] 2018-01-05 03:09
Thanks for your detailed reply, I will test the change hopefully today and let you know how it goes.

**Comment by mattslater** [comment] 2018-01-05 03:39
Thanks Catalin!

**Comment by catalinpan** [comment] 2018-01-07 19:39
I've managed to test on osx the script. I believe the problem is with the seq command. I have pushed a fix https://github.com/cststack/k8comp/commit/95b0bd5aa2bd1f6f4e5b09bf8eec60564bd1f051
On my tests everything seems to work on linux and osx.
```
brew install gnu-sed --with-default-names
brew install findutils --with-default-names
gem install --no-ri --no-rdoc hiera-eyaml hiera
curl -L https://raw.githubusercontent.com/cststack/k8comp/95b0bd5aa2bd1f6f4e5b09bf8eec60564bd1f051/bin/k8comp -o /usr/local/bin/k8comp
chmod +x /usr/local/bin/k8comp
```
Please let me know if this fixes the issue.
Thanks!

**Comment by catalinpan** [comment] 2018-02-10 00:41
This issue should now be resolved with this commit https://github.com/cststack/k8comp/commit/706473cfa1731d924d7ee226e35d9bf62a3beb67
[Here](https://cststack.github.io/k8comp/01-install/01-requirements/#mac-os-dependencies) can be found also the dependencies. 
Feel free to reopen the issue if this doesn't resolve the problem.

**Closed as completed by catalinpan** 2018-02-10 00:41 UTC
